spring:
  application:
    name: 'app-agendamento-backend'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Fortaleza
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/appagendamentodb
    username: agendamentobackend
    password: 123789
springdoc:
  open-api:
    titulo: 'App Agendamento BackEnd'
    descricao: 'API responsável pelo gerenciamento de todos os recursos do aplicativo App Agendamento'
    versao: '1.0.0'